name: lint

on:
  push:
    branches: [ main ]

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run ktlint
        run: |
          ./gradlew ktlintCheck --daemon
